language: rust
rust:
  - nightly
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
    - build
sudo: required

install:
  - export CC=gcc-7
  - export CXX=g++-7
  - ./build_utils/kcov.sh
  - ./build_utils/capnp.sh
  - ./build_utils/annoy.sh

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-kcov || echo "Cargo kcov already installed"

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - rustdoc --test readme.md -L target
  - cargo build --release

after_success:
  - cargo kcov --all --verbose --no-clean-rebuild --coveralls

before_deploy:
  - cargo doc
  - mkdir public
  - cp -r target/doc public/
  - mkdir dist/
  - cp -r target/release/knn_serving dist/.
  - tar cvf dist.tar.gz dist/

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: public
    keep-history: true
    on:
      branch: master
  - provider: releases
    skip-cleanup: true
    api_key:
      secure: $GITHUB_TOKEN
    file: dist.tar.gz
    draft: true

notifications:
  email:
    on_success: never
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7
      - pkg-config
      - jq
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
