[package]
name = "annoy-rs"
version = "0.1.0"
authors = ["Charles Roussel <c.roussel@criteo.com>"]

[dependencies]
libc= "0.2"

[build-dependencies]
cc = "1.0"
bindgen = "0.43"

[dev-dependencies]
rand = "0.6"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"