[package]
name = "knn_serving_api"
version = "0.1.0"
authors = ["Charles Roussel <c.roussel@criteo.com>"]

[dependencies]
capnp = "0.9"
capnp-rpc = "0.9"
capnp-futures = "0.9"

[build-dependencies]
capnpc = "0.9"